### ISSUE TITLE
Cannot use after installation

### ISSUE THREAD

**Issue by qu-tan-um** [jiaqileng/QHDOPT#29]
I installed this package and I'm able to run the jupyter notebooks. However, when I tried to use the module outside. It says
```
Traceback (most recent call last):
  File "...", line 1, in <module>
    from qhdopt import QHD
  File "...", line 1, in <module>
    from qhdopt import QHD
ImportError: cannot import name 'QHD' from partially initialized module 'qhdopt' (most likely due to a circular import)
```

**Comment by PicksPeng** [comment]
Can you try to install with `pip install qhdopt`? We recently published the current version in PyPI, which works in our test environments.

**Comment by qu-tan-um** [comment]
I think the python import is working for me. 

Another point I mention last time is: is there a method to directly return the compiled results? For IonQ backend, I think there is some Dict to store it, and we can see the gates when turning on certain verbose levels, but I don't see a directly method to get the compiled gates.

**Comment by PicksPeng** [comment]
> Another point I mention last time is: is there a method to directly return the compiled results? For IonQ backend, I think there is some Dict to store it, and we can see the gates when turning on certain verbose levels, but I don't see a directly method to get the compiled gates.

This feature is added in the `ionq_patch` branch. You can find more details in my new email.

I will close this PR since the main issue is solved.
